### ISSUE TITLE
Screencasts link goes to designbytypeing.com instead of designbytyping.com

### ISSUE THREAD

**Issue by clintonhalpin** [mrmrs/mrmrs#4]
See screenshot

![screen shot 2015-02-13 at 6 03 36 pm](https://cloud.githubusercontent.com/assets/523933/6196838/cf3b74a0-b3aa-11e4-8a36-910c13d85433.png)

**Comment by mrmrs** [comment]
Lots like I fixed this in a separate commit. Thanks for letting me know though! Terribly embarrassing.
